---
title: "Welcome"
---

# A strong foundation, an exciting future

As part of a significant step forward in our journey, we rebranded in 2024 and adopted a new name to reflect this new state. We are now the National Institute for Modeling Biological Systems, housed as one of the [research centers and institutes](https://artsci.utk.edu/research-and-creative-activity/research-centers-and-institutes/) within the College of Arts & Sciences at the University of Tennessee, Knoxville. We’re still the NIMBioS you know and love and we are excited for this new chapter together.

We celebrate this pivotal point for NIMBioS and we express gratitude toward our founding director Dr. Lou Gross for the solid foundation NIMBioS was built upon.

Building on the strong start in life NIMBioS had as an NSF Synthesis Center, we still foster a vibrant community focused on creating new science with our models. We will continue bringing our community together as an intellectual hub for transdisciplinary research and education in the quantitative life sciences. We are focusing on our unique strength in modeling.

We are dedicated to supporting the research community and maintaining our status as an international leader, intellectual center, and emotional heart of the community of mathematical life scientists. How will we do it? We will lower the barriers for students and researchers to learn and accomplish goals within the field.

See more of our progress from 2021-4 the [NIMBioS Bragbook](https://www.nimbios.org/wp-content/uploads/2024/11/NIMBioS_FINALCOPY10.10.24.pdf)

# NIMBioS Legacy Page

We wouldn't be where we are today without all of the great work done by previous NIMBioS staff, leaders, researchers, and students. Our [Legacy website](https://legacy.nimbios.org/) contains all archived information dating back to the start of our institute.

