---
title: "Impact"
---

NIMBioS has been an integral part of advancing the field of mathematical biology since 2008. Our programs and results have enhanced collaborations between many different academic communities, fostering convergent research and education in the United States and the world. NIMBioS has successfully survived a critical transition point in the life of the Institute. Under its initial Synthesis Center grant from NSF (2008-2021), NIMBioS received approximately $34 million dollars to establish itself as a preeminent international research institute in mathematical biology.

The impacts from this endeavor helped shape more than a decade of progress across the entire field. At the close of the initial Center grant (non-renewable after 2021), we transitioned into a new phase in which the life of NIMBioS now relies predominantly on:

(1) providing research support and expertise in mathematical, computational, and quantitative methods, training, and outreach (either as fee-for-service through our recharge center, or as consultancies or direct subcontracts on external awards to our affiliates and staff) and, much more importantly
(2) catalyzing additional funding proposals from affiliated researchers. Get in touch with our grant writer today!

# Contribution to Public Policy and Infectious Disease Control

Contributed significantly to investigating numerous questions of direct public policy concern, particularly the analysis of the potential spread, impact and control of infectious diseases of zoonotic origin, including West Nile virus, anthrax, swine flu and mad cow disease.

# Engaging Participants

Actively engaged participants to ensure that NIMBioS events welcomed and supported our whole community.

# Bringing STEM to Everyone

Supported more than 280 specific education and outreach activities with more than 2,400 participants, including specific programs promoting equity in STEM.

# Over 450 Projects Supported

Supported more than 450 projects proposed by the science community, leading to the publication of more than 1100 peer-reviewed scientific articles in a variety of disciplines, from anthropology to zoology.

# 8,700 Visits and Counting

Included more than 8,700 visits by individuals from more than 55 countries in scientific collaborative activities.

# National Recognition 

Received recognition for NIMBioS-supported science and research in local, regional, national and international press including Science, Nature, The New York Times, the Los Angeles Times, CNN, National Public Radio, and other national media.

# Reached Wider Audiences During COVID-19

Broadened reach to wider audiences via live streaming infrastructure, which has hosted more than 5,000 virtual participants in NIMBioS activities. NIMBioS Interactive, a virtual collaborative space for the NIMBioS community, was developed in response to an increased emphasis on virtual events during the 2020-2021 COVID-19 pandemic.

# Online Educational Content

Produced a vast video library of more than 600 videos with more than 279,800 views and 2272 subscribers, featuring scientist interviews, science narratives, workshops, tutorials, seminars, webinars and other educational events.